---
- name: Prepare apm
- file: /usr/local/bin dest=/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm state=link


//  Install Shell Commands. This creates two symlinks in /usr/local/bin
apm -> /Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/apm
atom -> /Applications/Atom.app/Contents/Resources/app/atom.sh
